# Utilise l'image de base officielle Nginx
FROM nginx:latest
# Expose le port 80 par défaut (ce port sera modifié par ta méthode ChangePortDockerfile)
EXPOSE 80

# Lance Nginx en tant que processus principal
CMD ["nginx", "-g", "daemon off;"]

